language: scala
dist: xenial
jdk: openjdk8
if: tag IS blank
before_install:
- git fetch --tags
stages:
- name: test
- name: release
  if: branch = master AND type = push
jobs:
  include:
  - stage: test
    script: sbt +test
  - stage: release
    script: sbt ciReleaseTagNextVersion ciReleaseBintray
before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
env:
  global:
  - secure: noXlHOjXSznKULwdoKt/pwnpCjZBB4y5nhXqliRVdC/RbLCpYtBv6FNlT2bjN6nkiEAI7SA6JYQef+YqGMNkf1z2qHsQBiiGeTkrQMJEL31quIPyctTzFL3PJyUxNrbQPOeddjnrjYRk+KRkClVkS0XLEr2N6qKtg/9bWlF2J0bthfNWdxgRFnvDuh7rVbEGBXOTZe9Sd16z9QDqlyXP3sa/pYAbxs8DQdjVLPLR8aQazExuecSPG1KESFIi+69/09JW2isont/a7Et2L7DOZgGxBc4Y7Gdwsa74ZLqQmu4vK88u1/YJFPOKLOTrdEmG1Ocl1tYx3H669Ji2ZZPF7wN0QKzl9srd34raUbWZx1QNCRDSIFWtqTQnhJ/kMps+m+IgdxWcbSSHUYN9AKF+P4NVGVYKOK8VzCb3V8tO9dB1qjEvF3H2fSlj0+oYJnNK2CwOeztmyKeosBWcXzvt0biMAXqIJ2oAiX8XLjcDhQtWMIqROtdOiTDE93arxdNl7tQ6icy9kj+MbgUXg12FFrLYEaBAQzWR1N6r9+8+H4TjvpKKCRechtYNDpNG5dirpSPqKWdjZxyTfECvWGzB6UQsfr8qLgQJwoCj/JpcefykxlP2d4QXrzuTJXHxP+XPQgamgJ/NF/D2Cg/iSTfT76LGM5nt9wgepFLrZ7AeVqA=
  - secure: SwlFcZOShJWMnWsFD+XuyHgGLPWNRF74Z+nm/NrWeK+/NkeX71mAHDISeOI42/b4uVN2+GLcxvLXddq8eRv/dGbVHPhCoOKO0/JpEvpys6b0j67Gc1mIDjgXKz5kZodPuKv6F9hA4dOkeP7+2exzqB15dsdVndmC6y4IuZdVYeRnPwLa4DzvQ8s1YAbE/PPFqDNRiV4mxKNfPs+OCDN0I9q3QQxIWO7GcAjXpUCSEOCK9yg1bKFaKnwzSjRYC+vmuw6VAue1Vw025JljdcH3vrmghF961EM0LRMjQcOkaTD9FrdkpoBBGLKD6RvBg17C76OSrO8WxGo3B/b/h7AlX5x/9M83oN45Nbc3waF6F7a/JHE99rW74BEcQ90GBTXwWG1fBN+b4g49QumUVtoV54EKNUghYHHe24rm1zlCQYM+Xf3ZLomYcI0SHXXZ0xQSr775gBwomaDm3ppKtGP1RJGKUhqkaaiP+j4PUDYEdXpwLgfo8YJqjkrVi+w4bKM5xA/LUiVSOaYA/CN1reCNoUsZMzH0+JDNp0nU4tkJ9t/QmZMLA0zai2Tga+hh9w7L8zWHVZbPVsdQR1VFfOWTh8677ILtpBoOlRGzFoooMlO/BXdJz2SKKqRrZK0az55OmMwNXDyr1MPKoZBEmQLoRG63TJYkwcixcQ4TRt7YWPY=
